services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5002"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - product-service
      - order-service
      - inventory-service